version: '3.4'

services:
  api:
    build: api/
    expose: 
      - "8000"
    networks:
      - deploy_network
    container_name: api

  streamlit:
    build: streamlit/
    depends_on:
      - api
    ports: 
        - "8501:8501"
    networks:
      - deploy_network
    container_name: streamlit

networks:
  deploy_network:
    driver: bridge
